name: Spawnalcraft
main: com.spinalcraft.spawnalcraft.Spawnalcraft
version: 1.0

depend: [Spinalpack]

commands:
  spawnalize:
    description: Set a spawn location
    usage: /spawnalize
    permission: spawnalcraft.spawnalize
    permission-message: No touchy.
  
  spawnal:
    description: Teleport to spawn
    usage: /spawnal
    permission: spawnalcraft.spawnal
    permission-message: No touchy.