name: Spawnalcraft
main: com.spinalcraft.spawnalcraft.Spawnalcraft
version: 1.0

depend: [Spinalpack]

commands:
  spawnalize:
    description: Set a spawn location
    usage: Usage - /spawnalize
    permission: spawnalcraft.spawnalize
    permission-message: No!
  
  spawnal:
    description: Teleport to spawn
    usage: Usage - /spawnal
    permission: spawnalcraft.spawnal
    permission-message: No!

  updatemotd:
    description: Reload the message of the day from motd.txt
    usage: Usage - /updatemotd
    permission: spawnalcraft.motd
    permission-message: No!
  
  spawnalcraft:
    description: Access internal commands
    usage: Usage - /spawnalcraft
    permission: spawnalcraft.spawnalcraft
    permission-message: No!
    